require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LoungesController do

  # This should return the minimal set of attributes required to create a valid
  # Lounge. As you add validations to Lounge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LoungesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lounges as @lounges" do
      lounge = Lounge.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lounges).should eq([lounge])
    end
  end

  describe "GET show" do
    it "assigns the requested lounge as @lounge" do
      lounge = Lounge.create! valid_attributes
      get :show, {:id => lounge.to_param}, valid_session
      assigns(:lounge).should eq(lounge)
    end
  end

  describe "GET new" do
    it "assigns a new lounge as @lounge" do
      get :new, {}, valid_session
      assigns(:lounge).should be_a_new(Lounge)
    end
  end

  describe "GET edit" do
    it "assigns the requested lounge as @lounge" do
      lounge = Lounge.create! valid_attributes
      get :edit, {:id => lounge.to_param}, valid_session
      assigns(:lounge).should eq(lounge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lounge" do
        expect {
          post :create, {:lounge => valid_attributes}, valid_session
        }.to change(Lounge, :count).by(1)
      end

      it "assigns a newly created lounge as @lounge" do
        post :create, {:lounge => valid_attributes}, valid_session
        assigns(:lounge).should be_a(Lounge)
        assigns(:lounge).should be_persisted
      end

      it "redirects to the created lounge" do
        post :create, {:lounge => valid_attributes}, valid_session
        response.should redirect_to(Lounge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lounge as @lounge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lounge.any_instance.stub(:save).and_return(false)
        post :create, {:lounge => {  }}, valid_session
        assigns(:lounge).should be_a_new(Lounge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lounge.any_instance.stub(:save).and_return(false)
        post :create, {:lounge => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lounge" do
        lounge = Lounge.create! valid_attributes
        # Assuming there are no other lounges in the database, this
        # specifies that the Lounge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lounge.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => lounge.to_param, :lounge => { "these" => "params" }}, valid_session
      end

      it "assigns the requested lounge as @lounge" do
        lounge = Lounge.create! valid_attributes
        put :update, {:id => lounge.to_param, :lounge => valid_attributes}, valid_session
        assigns(:lounge).should eq(lounge)
      end

      it "redirects to the lounge" do
        lounge = Lounge.create! valid_attributes
        put :update, {:id => lounge.to_param, :lounge => valid_attributes}, valid_session
        response.should redirect_to(lounge)
      end
    end

    describe "with invalid params" do
      it "assigns the lounge as @lounge" do
        lounge = Lounge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lounge.any_instance.stub(:save).and_return(false)
        put :update, {:id => lounge.to_param, :lounge => {  }}, valid_session
        assigns(:lounge).should eq(lounge)
      end

      it "re-renders the 'edit' template" do
        lounge = Lounge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lounge.any_instance.stub(:save).and_return(false)
        put :update, {:id => lounge.to_param, :lounge => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lounge" do
      lounge = Lounge.create! valid_attributes
      expect {
        delete :destroy, {:id => lounge.to_param}, valid_session
      }.to change(Lounge, :count).by(-1)
    end

    it "redirects to the lounges list" do
      lounge = Lounge.create! valid_attributes
      delete :destroy, {:id => lounge.to_param}, valid_session
      response.should redirect_to(lounges_url)
    end
  end

end
